spring.application.name=doctorbooking

spring.datasource.url=jdbc:mysql://localhost:3306/doctor_booking?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Maity.9687

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081